---
title: "Heatmaps of clusters responding to day/night in co-expression network"
output: html_notebook
---

Importing the table with expression values of the modules

```{r}
library(dplyr)
library(tidyverse)
library(RColorBrewer)
library(scico)
library(pheatmap)

Exp_table_long_z <- read.csv("/home/santosrac/Projects/UGA_RACS/Transcriptome/paper2025/paper2025/Exp_table_long_z.txt",
#Exp_table_long_z <- read.csv("Exp_table_long_z.txt",
                 sep = "\t",
                 header = TRUE)

day_period_responding_modules <- c(10,12,16,1,22,25,26,29,30,31,39,40,45,52,5,7,8,9)

# Filter the data based on the list of modules
Exp_table_long_z_filtered <- Exp_table_long_z %>%
    filter(module %in% day_period_responding_modules)

## make eigengenes heatmap for modules responding to day-night
# make wide matrix for logTPM
Exp_wide <- Exp_table_long_z_filtered %>%
  select(Name, SampleName, logTPM) %>%
  pivot_wider(names_from = SampleName, values_from = logTPM)

# Set Name as rownames and remove the Name column (transform into a matrix)
Exp_wide_matrix <- Exp_wide %>%
  column_to_rownames(var = "Name")


get_eigen <- function(module_no){
        genes <- Exp_table_long_z_filtered %>% filter(module == module_no) %>% distinct(Name) %>% pull(Name)
        df <- Exp_wide_matrix[genes,]
        pca <- prcomp(t(df))
        eigen <- pca$x[,1]
        # Calculate module eigengene as the mean expression across all genes in the module
        module_mean <- colMeans(df, na.rm = TRUE)
        # Check correlation between PC1 and module mean
        correlation <- cor(eigen, module_mean)
        # If correlation is negative, flip the eigengene
	if(correlation < 0) {
                eigen <- -eigen
        
	}
        row <- data.frame(eigen = t(eigen), row.names = paste0("module_",module_no))
        return(row)
}


results_list <- list()
loop_modules <- levels(as.factor(Exp_table_long_z_filtered$module))

for (module in loop_modules){
        result <- get_eigen(module)
        results_list[[as.character(module)]] <- result
	cat("Module:", module, "\n")
}

results_df <- bind_rows(results_list, .id = "module")

eigen_mat <- results_df %>%
	select(-module) %>%
	as.matrix()

sample_info <- data.frame(SampleName = colnames(eigen_mat))
sample_info$Period <- ifelse(grepl("eigen.exp_day", sample_info$SampleName, ignore.case = TRUE), "Midday", "Midnight")
row.names(sample_info) <- sample_info$SampleName
sample_info$SampleName <- NULL

head(sample_info)

ann_colors = list(Period = c(Midday = "#FFD700", Midnight = "#1E3A8A"))

rownames(eigen_mat) <- gsub("_", " ", rownames(eigen_mat))

p <- pheatmap(eigen_mat,
	 scale = "row",
	 annotation_col = sample_info,
	 show_rownames = T,
	 show_colnames = F,
	 annotation_colors = ann_colors,
	 col = scico(100, palette = 'vikO'),
	 cluster_cols = T,
	 cluster_rows = T,
	 cellwidth = 1,
	 cellheight = 9)


grob <- p$gtable


pdf("heatmap_eigengenes.pdf", width = 9, height = 4)
grid::grid.newpage()
grid::grid.draw(grob)
dev.off()

png("heatmap_eigengenes.png", res = 300, width = 2.4*1200, height = 2500)
grid::grid.newpage()
grid::grid.draw(grob)
dev.off()

########################################
# make heatmaps for all responding modules #
########################################

get_module_heatmap <- function(module_no){
	genes <- Exp_table_long_z_filtered %>% filter(module == module_no) %>% distinct(Name) %>% pull(Name)
        df <- Exp_wide_matrix[genes,]
        breaksList = seq(-3, 3, by = 0.1)
        p <- pheatmap(df,
                         main = paste0("Module: ", module_no),
                         scale = "row",
                         annotation_col = sample_info,
                         show_rownames = F,
                         show_colnames = F,
                         breaks = breaksList,
                         annotation_colors = ann_colors,
                         color = scico(length(breaksList), palette = 'vikO'),
                         cluster_cols = T,
                         cluster_rows = T,
                         cellwidth = 1,
                         cellheight = 1.3)
	grob <- p$gtable

	pdf(paste0("module_", module_no, "_heatmap", ".pdf"), width = 9, height = 4)
        grid::grid.newpage()
        grid::grid.draw(grob)
        dev.off()

        png(paste0("module_", module_no, "_heatmap", ".png"), res = 300, width = 2.4*1200, height = 2500)
        grid::grid.newpage()
        grid::grid.draw(grob)
        dev.off()
}

for (module in loop_modules){
        get_module_heatmap(module)
        cat("Module:", module, "\n")

}

```

```{r}
library(pheatmap)

# Filter for genes in module 1
module1_genes <- Exp_table_long_z_filtered %>%
    filter(module == 1)
module5_genes <- Exp_table_long_z_filtered %>%
    filter(module == 5)
module9_genes <- Exp_table_long_z_filtered %>%
    filter(module == 9)

head(module1_genes)

# Prepare matrix: rows = genes, columns = samples
heatmap_mat <- module1_genes %>%
    select(Name, SampleName, z.score) %>%
    tidyr::pivot_wider(names_from = SampleName, values_from = z.score) %>%
    tibble::column_to_rownames("Name") %>%
    as.matrix()

# Create annotation_col from columns in heatmap_mat
sample_info <- data.frame(SampleName = colnames(heatmap_mat))
sample_info$Period <- ifelse(grepl("exp_day", sample_info$SampleName, ignore.case = TRUE), "Day", "Night")
row.names(sample_info) <- sample_info$SampleName
sample_info$SampleName <- NULL
head(sample_info)

ann_colors = list(
    Period = c(Day = "#FFD700", Night = "#1E3A8A")
)

# Export heatmap to PDF with high resolution
pdf("module1_heatmap.pdf", width = 40, height = 30)
pheatmap(heatmap_mat, 
            cluster_rows = FALSE,
            cluster_cols = TRUE,
            scale = "row",
            show_rownames = TRUE,
            show_colnames = FALSE,
            annotation_col = sample_info,
            annotation_colors = ann_colors,
            main = "Module 1 (Nucleic Acid Binding)",
            annotation_legend = TRUE,
            fontsize = 12,
            fontsize_row = 10,
            cellwidth = 6,
            cellheight = 10)
dev.off()

heatmap_mat <- module5_genes %>%
    select(Name, SampleName, z.score) %>%
    tidyr::pivot_wider(names_from = SampleName, values_from = z.score) %>%
    tibble::column_to_rownames("Name") %>%
    as.matrix()

pdf("module5_heatmap.pdf", width = 40, height = 30)
pheatmap(heatmap_mat, 
            cluster_rows = FALSE,
            cluster_cols = TRUE,
            scale = "row",
            show_rownames = TRUE,
            show_colnames = FALSE,
            annotation_col = sample_info,
            annotation_colors = ann_colors,
            main = "Module 5 (Heat Stress Response)",
            annotation_legend = TRUE,
            fontsize = 12,
            fontsize_row = 10,
            cellwidth = 6,
            cellheight = 10)
dev.off()

# Cluster columns within each group defined in sample_info$Period and reorder columns accordingly

library(dendextend)

# Function to get column order for each group
get_group_col_order <- function(mat, group_labels) {
    unique_groups <- unique(group_labels)
    ordered_cols <- c()
    for (grp in unique_groups) {
        grp_cols <- which(group_labels == grp)
        if (length(grp_cols) > 1) {
            # Cluster columns within group
            d <- dist(t(mat[, grp_cols, drop = FALSE]))
            hc <- hclust(d)
            ordered_grp_cols <- grp_cols[order.dendrogram(as.dendrogram(hc))]
        } else {
            ordered_grp_cols <- grp_cols
        }
        ordered_cols <- c(ordered_cols, ordered_grp_cols)
    }
    return(ordered_cols)
}

# Module 1 genes
heatmap_mat1 <- module1_genes %>%
    select(Name, SampleName, z.score) %>%
    tidyr::pivot_wider(names_from = SampleName, values_from = z.score) %>%
    tibble::column_to_rownames("Name") %>%
    as.matrix()

# Ensure sample_info matches columns
sample_info1 <- data.frame(SampleName = colnames(heatmap_mat1))
sample_info1$Period <- ifelse(grepl("exp_day", sample_info1$SampleName, ignore.case = TRUE), "Day", "Night")
row.names(sample_info1) <- sample_info1$SampleName
sample_info1$SampleName <- NULL

# Get new column order
col_order <- get_group_col_order(heatmap_mat1, sample_info1$Period)
heatmap_mat1 <- heatmap_mat1[, col_order]
sample_info1 <- sample_info1[col_order, , drop = FALSE]

pdf("module1_heatmap.pdf", width = 40, height = 30)
pheatmap(heatmap_mat1, 
                 cluster_rows = FALSE,
                 cluster_cols = FALSE,
                 scale = "row",
                 show_rownames = TRUE,
                 show_colnames = FALSE,
                 annotation_col = sample_info1,
                 annotation_colors = ann_colors,
                 main = "Module 1 (Nucleic Acid Binding)",
                 annotation_legend = TRUE,
                 fontsize = 18,
                 fontsize_legend = 16,
                 fontsize_row = 10,
                 cellwidth = 6,
                 cellheight = 10)
dev.off()


# Module 5 genes
heatmap_mat5 <- module5_genes %>%
    select(Name, SampleName, z.score) %>%
    tidyr::pivot_wider(names_from = SampleName, values_from = z.score) %>%
    tibble::column_to_rownames("Name") %>%
    as.matrix()

# Ensure sample_info matches columns
sample_info5 <- data.frame(SampleName = colnames(heatmap_mat5))
sample_info5$Period <- ifelse(grepl("exp_day", sample_info5$SampleName, ignore.case = TRUE), "Day", "Night")
row.names(sample_info5) <- sample_info5$SampleName
sample_info5$SampleName <- NULL

# Get new column order
col_order <- get_group_col_order(heatmap_mat5, sample_info5$Period)
heatmap_mat5 <- heatmap_mat5[, col_order]
sample_info5 <- sample_info5[col_order, , drop = FALSE]

pdf("module5_heatmap.pdf", width = 38, height = 12)
pheatmap(heatmap_mat5, 
                 cluster_rows = FALSE,
                 cluster_cols = FALSE,
                 scale = "row",
                 show_rownames = TRUE,
                 show_colnames = FALSE,
                 annotation_col = sample_info5,
                 annotation_colors = ann_colors,
                 main = "Module 5 (Heat Stress Response)",
                 annotation_legend = TRUE,
                 fontsize = 18,
                 fontsize_legend = 16,
                 fontsize_row = 10,
                 cellwidth = 6,
                 cellheight = 10)
dev.off()

# Module 9 genes
heatmap_mat9 <- module9_genes %>%
    select(Name, SampleName, z.score) %>%
    tidyr::pivot_wider(names_from = SampleName, values_from = z.score) %>%
    tibble::column_to_rownames("Name") %>%
    as.matrix()

# Ensure sample_info matches columns
sample_info9 <- data.frame(SampleName = colnames(heatmap_mat9))
sample_info9$Period <- ifelse(grepl("exp_day", sample_info9$SampleName, ignore.case = TRUE), "Day", "Night")
row.names(sample_info9) <- sample_info9$SampleName
sample_info9$SampleName <- NULL

# Get new column order
col_order <- get_group_col_order(heatmap_mat9, sample_info9$Period)
heatmap_mat9 <- heatmap_mat9[, col_order]
sample_info9 <- sample_info9[col_order, , drop = FALSE]

pdf("module9_heatmap.pdf", width = 38, height = 8)
pheatmap(heatmap_mat9, 
                 cluster_rows = FALSE,
                 cluster_cols = FALSE,
                 scale = "row",
                 show_rownames = TRUE,
                 show_colnames = FALSE,
                 annotation_col = sample_info9,
                 annotation_colors = ann_colors,
                 main = "Module 9 (Photosynthesis)",
                 annotation_legend = TRUE,
                 fontsize = 18,
                 fontsize_legend = 16,
                 fontsize_row = 10,
                 cellwidth = 6,
                 cellheight = 10)
dev.off()
```
